### PR TITLE
Add parameter to initialize partially parsed METARs

### PR DESCRIPTION
**Pull request by 1kastner**
Offer a way to convert ParserErrors into warnings when minor information was not understood.

### CODE REVIEW

**Comment by 1kastner** [comment]
@tomp do you have any plans to merge this?

**Comment by tomp** [comment]
I don't think this is helpful, unfortunately.  If there are unparsed groups in the METAR code, it's an error.  The proper way to handle an error like this in Python is to throw an exception. If you think the generic exception that's currently thrown should be more specific, I'd be open to creating a more specific exception for the case that you want to be able to ignore.  One way or the other, the correct way to handle this is for you (the client) to catch my exception, rather than for me to suppress the error.

**Comment by 1kastner** [comment]
Under some circumstances we are only interested in some partial information of the METAR. In my project e.g. I was only interested in cloud cover. I did not care whether the wind was correctly parsed (see e.g. here: https://github.com/tomp/python-metar/issues/26). But your exception handling would have forced me to totally ignore that measurement or alternatively to write my own parser. In the readme you say that some local formats are not supported and as I am not an expert on METARs I was not sure which of these issues were linked to that fact. So I believe that it is not necessary to see it as an error if some details could not be parsed.  If those details are not the ones you are currently interested in there might be nothing bad about it.

**Comment by 1kastner** [comment]
There are still #26 #27 #28 out there which could benefit from this pull request. For a long time no changes...

**Comment by WeatherGod** [comment]
Just came across this METAR from aviationweather.gov:

 `'K9L2 100958Z AUTO 33006KT 10SM CLR M A3007 RMK AO2 SLPNO FZRANO $'`

That silly 'M' there is messing up everything for me. In my case, I am loading up all of the metars I have for a given hour into a Pandas Dataframe. I want my dataframe to record that there is a maintence indicator on, and that there are some other things turned off. Right now, I am completely blind to the fact that this station is broken and putting out bad metars in my code.

**Comment by WeatherGod** [comment]
Also, as a side note, I would suggest modifying this implementation slightly so that a flag is set such as "self.is_valid = False" or something, in addition to emitting the warning.

**Comment by 1kastner** [comment]
@WeatherGod Feel free to take my changes and adjust them as another PR. The best way to express the idea (which is still a bit vague to me) is to show it.

**Comment by WeatherGod** [comment]
perhaps I might do that... I have to be careful not to let myself down a rabbit-hole of a bunch of little changes I have been thinking of, particularly to allow for others to easily extend the parsing capabilities by making a subclass, or passing in a list of additional regexs/function tuples.

But the basic idea with what I was saying is that after the object creation, I should be able to check an attribute to know if the metar is completely valid or not. Warnings, while useful, are more intended for logs.

**Comment by WeatherGod** [comment]
Oh, and for those who might be interested in a possible work-around (I do deeply apologize for the crass language for this package name and its documentation, but it does work): https://pypi.python.org/pypi/fuckit

**Comment by 1kastner** [comment]
I am curious how you intend to solve it, looking forward to it!

**Comment by akrherz** [comment]
Hi @WeatherGod , the `is_valid` idea is problematic as this library does not cover the full METAR specification.  Currently, it emits exceptions for valid METARs.  I hope to engage some other meteorology python dudes at Unidata next week to discuss thoughts on a path forward for a METAR parser, perhaps something embedded within `metpy`, we shall see :)

**Comment by 1kastner** [comment]
@akrherz With the current project velocity of this project using metpy is the better way to go I guess.

**Comment by WeatherGod** [comment]
The `is_valid` name was just a suggestion. Maybe `incomplete_parse` might
be a better name?

Metpy is trying to position itself as a replacement to gempak. Last time I
checked, gempak doesn't decode metars, so I doubt it'll adopt it. Thoughts,
@dopplershift?

I will say this, at this particular moment, my employer requires a metar
decoder in python that is capable of decoding info from aviationweather.gov.
Now, how far he wants me to go with this, I am not sure (he might just want
me to drop these "invalid" metars and move on), but it could mean that I'll
need to fork this package.

**Comment by akrherz** [comment]
@WeatherGod GEMPAK has [decoded metars](https://www.unidata.ucar.edu/software/gempak/man/prog/dcmetr.html) for a very long time :)

**Comment by WeatherGod** [comment]
Ah, good to know. The last time I regularly worked with gempak was in
undergrad, and that was mostly for learning about potential vorticity and
eta levels...

**Comment by WeatherGod** [comment]
I created #36 as an initial step.

**Comment by WeatherGod** [comment]
I also created #37, which is a tiny change that should make it possible for users to modify the set of regexes and handlers to use for parsing. See the example there for some ideas.

**Comment by dopplershift** [comment]
FYI, my plan is to implement a true parser for METARS, as in true CS parser, rather than abusing regexes for human-coded text: Unidata/metpy#70

**Pull request closed without merging**
